### ISSUE TITLE
Goals

### ISSUE THREAD

**Issue by dastrong** [chingu-voyages/geckos-project-16#3]
We should set goals for ourselves and hold ourselves accountable to them

**Comment by diskomotech** [comment]
My goals

- Learn and build in React.
- Learn how to utilise unit testing and debugger tools.
- Try pair programming.

**Comment by dastrong** [comment]
My goals this week
- Set up and guide team members through the beginning stages of our project
- Gain experience with git in a team environment
- Help team members learn React and achieve their weekly goals
- Complete our first sprint

**Comment by dhairyadwivedi** [comment]
Goals:
• Learn React and apply it to the project.
• Read up more on the tools we'll be using.

**Comment by diskomotech** [comment]
Week 2 goals:

- Build more complicated component(s)
- Learn how to style components with ReactSemanticUI

**Comment by dhairyadwivedi** [comment]
Week 2 Goals:
• Add styling to the NavBar component

**Comment by dastrong** [comment]
Week 2 Goals:
- Assist team members with their components
- Show team members some refactor opportunities
- Start to assemble components into a working app
  - Add routing

**Comment by diskomotech** [comment]
Week 3 goals (to 31st Dec)
- Finish search sidebar component
- Add styling & colour to view listing page

**Comment by dastrong** [comment]
Week 3 goals (to 31st Dec)

- Style at least 2 components
- Think about a possible backend and ways to best implement it
- Remove some of the lorem ipsum in components with actual content
