### ISSUE TITLE
Weekly Sprint To Do List

### ISSUE THREAD

**Issue by dastrong** [chingu-voyages/geckos-project-16#5]
Plan our sprint for the 2nd-9th of December

**Comment by diskomotech** [comment]
- Confirm everyone is comfortable and has environment totally set-up as early as possible.
- Have a finished design wireframe/mockup.

What else?

**Comment by dastrong** [comment]
If anyone has any questions about getting **set up**, the **workflow** or the **wireframe** please ask before you choose/take a component to build.
