### ISSUE TITLE
SEO?

### ISSUE THREAD

**Issue by dastrong** [chingu-voyages/geckos-project-16#77]
Does anyone wanna look into SEO? 

Our HTML file is pretty bare..

**Comment by dastrong** [comment]
@diskomotech this is still in progress since we're still going to use react-snapshot or snap, correct?

**Comment by diskomotech** [comment]
Yeah still in progress. I just wanted to merge what's been done thus far

**Comment by diskomotech** [comment]
Waiting on finalization of site content and then will use react-snapshot to improve SEO
