### ISSUE TITLE
Random Facts

### ISSUE THREAD

**Issue by dastrong** [chingu-voyages/geckos-project-16#87]
Found these two random fact APIs: [cats](https://catfact.ninja/fact) and [dogs](https://dog-api.kinduff.com/api/facts).

Each API call to them return a different interesting fact. I thought it would be neat if we could incorporate them somehow. 

Maybe have either or both displayed in a Segment styled similar to the `Footer` or `Disclaimer`. Perhaps it could be placed between those two? Or above the disclaimer... or below the Footer...

What does everyone think?

**Comment by dhairyadwivedi** [comment]
The slider idea seems good, we should try that.

**Comment by dastrong** [comment]
Closing this issue and activity on this repo. 

For further development and long-term support go [here](https://github.com/dastrong/RescueKorea).
